FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG DB_CONNECT
ENV DB_CONNECT=$DB_CONNECT
ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET
ARG REDIS_PASSWORD
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ARG AZURE_STORAGE_CONNECTION_STRING
ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
ARG AZURE_STORAGE_ACCOUNT_KEY
ENV AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY
ARG AZURE_STORAGE_ACCOUNT_NAME
ENV AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_ACCOUNT_NAME
EXPOSE 3001
CMD ["npm", "start"]
